version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202111-02
jobs:
  build:
    executor: machine-executor
    working_directory: ~/nginx-build
    steps:
      - checkout
      - run: |
          echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_ID --password-stdin
          chmod +x docker-entrypoint.sh
          chmod +x envsubst-on-templates.sh
          chmod +x tune-worker-processes.sh
          chmod +x env.sh
          source env.sh
          sudo docker build . -t $DOCKER_HUB_ID/nginx:$NGINX_VERSION-rtmp-geoip2-alpine --no-cache
          docker push $DOCKER_HUB_ID/nginx:$NGINX_VERSION-rtmp-geoip2-alpine
  test:
    executor: machine-executor
    working_directory: ~/nginx-build
    steps:
      - run: |
          docker pull $DOCKER_HUB_ID/nginx:$NGINX_VERSION-rtmp-geoip2-alpine
          docker run -t --name webserver --rm  $DOCKER_HUB_ID/nginx:$NGINX_VERSION-rtmp-geoip2-alpine nginx -v

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build